spring:
  application:
    name: meat

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meat_market_db}
    username: ${SPRING_DATASOURCE_USERNAME:meat_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:Xaero891500}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        default_schema: meat_shop
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# ЭТУ ЧАСТЬ ПЕРЕМЕСТИТЕ ВНЕ БЛОКА spring:
app:
  upload:
    dir: ${APP_UPLOAD_DIR:./uploads}
    base-url: http://localhost:8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: false

server:
  port: 8080

logging:
  level:
    org.hibernate: INFO
    org.springframework: INFO
    ru.xaero.meat: DEBUG
  file:
    name: /app/logs/application.log